#!/bin/bash

echo "Synthesize design..."
yosys  -q -p "synth_ice40 -top top -blif j1a.blif -abc2" j1a.v uart.v j1.v stack2.v 

echo "Place and Route..."
arachne-pnr -r -p ja1.pcf j1a.blif -o j1a.txt -d 5k

echo "Create Bitstream..."
icepack j1a.txt j1a0.bin
# icemulti -p0 j1a0.bin > j1a.bin

echo "Timing Analysis..."
icetime -c 48 -t -d up5k -r time.txt j1a.txt 

echo "Finished."
